version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: infra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - infra_net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: infra-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8081:8025"
    networks:
      - infra_net

networks:
  infra_net:

volumes:
  postgres_data:
