services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: doctorapp
    mem_limit: 512m
    cpus: 0.5
    volumes:
      - ../backend:/app
      - ../logs:/var/logs
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
