services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: doctorapp
    mem_limit: 512m
    cpus: 0.5
    volumes:
      - ../../logs:/var/logs
      - /home/ubuntu/app/wallet:/app/wallet:ro
    environment:
      SPRING_PROFILES_ACTIVE: oracle
    ports:
      - "8080:8080"
